version: '2'

services:
    dnsmasq:
        image: andyshinn/dnsmasq
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        cap_add:
            - NET_ADMIN
        command: --log-facility=-
        volumes:
            - ./.data/dnsmasq.conf:/etc/dnsmasq.conf
            - ./.data/dnsmasq.d:/etc/dnsmasq.d
    redis:
        image: redis
        ports: 
            - "6379:6379"
    db:
        image: mariadb:10.1
        volumes:
            - "./.data/db:/var/lib/mysql"
        image: mariadb:10.1
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            - LOOPBACK_ADDR
            - XDEBUG_PORT
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
            - ./logs/php:/var/log/php:cached
        links:
            - redis
            - db
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
